#!/usr/bin/env bash

set -euo pipefail

source /home/hff/.keys/pongo-minio-restic-service-account.env

restic \
	--repo s3:http://pongo:9000/hff-restic \
	--password-file /home/hff/.keys/pongo-restic.txt \
	backup \
	--exclude=".ansible" \
	--exclude=".cache" \
	--exclude="void-packages" \
	--exclude="quickemu" \
	/home/hff \
	&& curl https://hc-ping.com/b5d37ac7-1610-40d3-ac0f-025af1219fd7

