#!/usr/bin/env bash

set -euo pipefail

source /home/hff/.keys/pongo-minio-restic-service-account.env

restic \
	--repo s3:http://pongo:9000/hff-restic \
	--password-file /home/hff/.keys/pongo-restic.txt \
	--path /home/hff \
	--host desk \
	--target / \
	--exclude="/home/hff/.mozilla" \
	--exclude="/home/hff/.bin" \
	--exclude="/home/hff/.cargo" \
	--exclude="/home/hff/.keys" \
	--exclude="/home/hff/.kube" \
	--exclude="/home/hff/.ssh" \
	--exclude="/home/hff/workstation-setup" \
	--exclude="/home/hff/.local/share/chezmoi" \
	restore latest

