- name: "Install Applications"
  hosts: localhost
  become: true

  tasks:
    # REGULAR
    - name: Install from regular repositories
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - xtools
        - make
        - vim
        - restic
        - tmux
        - zsh

        - tree
        - jq
        - htop
        - btop
        - iftop
        - rclone
        - xinput  # for mouse key reassignment
        - the_silver_searcher
        - ffmpeg

        - vscode
        - docker
        - docker-compose
        - go
        - git-lfs
        - git-crypt
        - gcc
        - github-cli
        - kubectl
        - kubernetes-helm

        - pavucontrol
        - chromium
        - inkscape
        - vlc
        - Signal-Desktop

        - syncthing
        - tesseract-ocr
        - cifs-utils
