- name: "Install Applications"
  hosts: localhost
  become: true

  tasks:
    # REGULAR
    - name: Install from regular repositories
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git-lfs
        - git-crypt
        - restic
        - age
        - jq
        - tmux
        - zsh
        - tree
        - pavucontrol
        - chromium-browser
        - htop
        - btop
        - iftop
        - python3-venv
        - inkscape

    # OTHER REPOS
    - name: Add repo keys
      apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - https://cli.github.com/packages/githubcli-archive-keyring.gpg
        - https://packages.cloud.google.com/apt/doc/apt-key.gpg
        - https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        - https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - deb https://cli.github.com/packages stable main
        - deb https://apt.kubernetes.io/ kubernetes-xenial main
        - deb http://repository.spotify.com stable non-free
        - deb https://packages.cloud.google.com/apt cloud-sdk main

    - name: Install from external repositories
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - gh
        - kubectl
        - spotify-client
        - google-cloud-cli

    # FROM DEBS
    - name: Install apps from deb packages
      apt:
        deb: "{{ item }}"
      loop:
        - https://downloads.slack-edge.com/releases/linux/4.25.0/prod/x64/slack-desktop-4.25.0-amd64.deb
        - https://az764295.vo.msecnd.net/stable/57fd6d0195bb9b9d1b49f6da5db789060795de47/code_1.67.0-1651667246_amd64.deb
        - https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
