- name: "Install Applications"
  hosts: localhost
  become: true

  tasks:
    # REGULAR
    - name: Install from regular repositories
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git-lfs
        - git-crypt
        - restic
        - age
        - jq
        - tmux
        - zsh
        - tree
        - pavucontrol
        - chromium-browser
        - htop
        - btop
        - iftop
        - python3-venv
        - inkscape
        - rclone
        - cifs-utils
        - syncthing
        - silversearcher-ag
        - ffmpeg
        - vlc
