- name: Setup periodic backups
  hosts: localhost
  become: true

  tasks:
    - name: daily cron to backup to pongo
      cron:
        name: backup hff home to pongo
        job: backup
        user: hff
        hour: "9"
