- name: "Install Applications"
  hosts: localhost
  become: true

  tasks:
    # TASK
    - name: Check if task is installed
      stat:
        path: /usr/local/bin/task
      register: task

    - name: Unarchive task
      unarchive:
        src: "https://github.com/go-task/task/releases/download/v3.13.0/task_linux_amd64.tar.gz"
        dest: /tmp
        remote_src: true
      when: not task.stat.exists

    - name: Install task
      copy:
        src: /tmp/task
        dest: /usr/local/bin/task
        remote_src: true
        mode: a+x
      when: not task.stat.exists

    # ELM
    - name: Check if elm is installed
      stat:
        path: /usr/local/bin/elm
      register: elm

    - name: Download elm
      get_url:
        url: "https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz"
        dest: /tmp/elm.gz
      when: not elm.stat.exists

    - name: Unarchive elm
      command:
        cmd: gunzip /tmp/elm.gz
        creates: /tmp/elm
      when: not elm.stat.exists

    - name: Install elm
      copy:
        src: /tmp/elm
        dest: /usr/local/bin/elm
        remote_src: true
        mode: a+x
      when: not elm.stat.exists

    # MINIO
    - name: Check if minio is installed
      stat:
        path: /usr/local/bin/mc
      register: minio

    - name: Download minio
      get_url:
        url: https://dl.min.io/client/mc/release/linux-amd64/mc
        dest: /tmp/mc
      when: not minio.stat.exists

    - name: Install minio
      copy:
        src: /tmp/mc
        dest: /usr/local/bin/mc
        remote_src: true
        mode: a+x
      when: not minio.stat.exists
    

    # KUBECTX
    - name: Check if kubectx is installed
      stat:
        path: /usr/local/bin/kubectx
      register: kubectx

    - name: Unarchive kubectx
      unarchive:
        src: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"
        dest: /tmp
        remote_src: true
      when: not kubectx.stat.exists

    - name: Install kubectx
      copy:
        src: /tmp/kubectx
        dest: /usr/local/bin/kubectx
        remote_src: true
        mode: a+x
      when: not kubectx.stat.exists

    # KUBENS
    - name: Check if kubens is installed
      stat:
        path: /usr/local/bin/kubens
      register: kubens

    - name: Unarchive kubens
      unarchive:
        src: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens_v0.9.4_linux_x86_64.tar.gz"
        dest: /tmp
        remote_src: true
      when: not kubens.stat.exists

    - name: Install kubens
      copy:
        src: /tmp/kubens
        dest: /usr/local/bin/kubens
        remote_src: true
        mode: a+x
      when: not kubens.stat.exists
