- name: "Install Applications"
  hosts: localhost
  become: true

  tasks:
    - name: Check if kubectx is installed
      stat:
        path: /usr/local/bin/kubectx
      register: kubectx

    - name: Unarchive kubectx
      unarchive:
        src: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"
        dest: /tmp
        remote_src: true
      when: not kubectx.stat.exists

    - name: Install kubectx
      copy:
        src: /tmp/kubectx
        dest: /usr/local/bin/kubectx
        remote_src: true
        mode: a+x
      when: not kubectx.stat.exists
