- name: Install display manager
  hosts: localhost
  become: true

  tasks:
    - name: ly build dependencies
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - make
        - pam-devel
        - libxcb
        - linux-vt-setcolors

