- name: Install Docker, Compose and setup for hff
  hosts: localhost
  become: true

  tasks:
    - name: "Docker reqs"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: "Download GPG apt Key"
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg_armored

    - name: De-Armor GPG key
      command:
        cmd: gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /usr/share/keyrings/docker-archive-keyring.gpg_armored 
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
      no_log: false

    - name: "Docker repository"
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: "Install docker and compose"
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - docker-compose

    - name: "Add hff to docker group"
      user:
        append: true
        groups: docker
        name: hff
