- name: "Workstation Setup"
  hosts: localhost
  become: true

  tasks:
    # MISC
    - name: "Disable packagekitd so that it stops interfering"
      service:
        name: packagekit
        enabled: false
        state: stopped

    # Applications
    - name: "Install Slack"
      apt:
        deb: "{{ item }}"
      loop:
        - https://downloads.slack-edge.com/releases/linux/4.25.0/prod/x64/slack-desktop-4.25.0-amd64.deb
        - https://az764295.vo.msecnd.net/stable/57fd6d0195bb9b9d1b49f6da5db789060795de47/code_1.67.0-1651667246_amd64.deb

    # DOCKER
    - name: "Docker reqs"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: "Docker GPG apt Key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Docker repository"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: "Install docker and compose"
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: "Add hff to docker group"
      user:
        append: true
        groups: docker
        name: hff

    # Dist upgrade
    - name: "apt dist-upgrade"
      apt:
        update_cache: true
        upgrade: dist
