- name: "Install Quickemu deps"
  hosts: localhost
  become: true

  tasks:
    - name: Install deps
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - qemu
        - bash
        - coreutils
        - grep
        - jq
        - procps-ng
        - usbutils
        - util-linux
        - sed
        - socat
        - swtmp
        - wget
        - zsync
        - python3
        - spice-gtk
        - unzip
