- name: "Install Quickemu deps"
  hosts: localhost
  become: true

  tasks:
    - name: Install deps
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - qemu
        - bash
        - coreutils
        - grep
        - jq
        - python3
        - spice-gtk
        - unzip
