- name: "Setup rust"
  hosts: localhost
  become: true
  become_user: hff

  tasks:
    - name: Install rustup
      shell: set -o pipefail && bash -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.cargo"

    - name: Install rust stable
      shell: rustup default stable && cargo
      args:
        executable: /bin/bash
        chdir: "$HOME"

