- name: "Configure System"
  hosts: localhost
  become: true

  tasks:
    - name: "Disable packagekitd so that it stops interfering"
      service:
        name: packagekit
        enabled: false
        state: stopped

    - name: Remove system76-scheduler as it correlates with system crashing
      apt:
        name: system76-scheduler
        state: absent

    - name: "Install nvidia driver for GTX 650 Ti"
      apt:
        name: nvidia-driver-390
        state: present
