- name: "System related stuff"
  hosts: localhost
  become: true

  tasks:
    - name: Install packages
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - bluez
        - cups
        - cups-filters
        - system-config-printer
        - net-tools
        - avahi
        - nss-mdns
        - void-repo-nonfree
        - noto-fonts-ttf
        - noto-fonts-ttf-extra
        - noto-fonts-cjk
        - noto-fonts-emoji
        - chrony

    - name: Enable services
      runit:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - cupsd
        - avahi-daemon
        - bluetoothd
        - chronyd

    - name: make sure hff is added to certain groups
      user:
        name: hff
        groups: "{{ item }}"
        append: yes
      loop:
        - audio
        - video
        - plugdev
        - wheel
        - bluetooth
        - users
        - docker
        - lp
        - lpadmin
        - dialout
        - storage
        - kvm

    - name: ensure members of storage group can mount stuff
      template:
        src: ./mount-disks-polkit-rules.j2
        dest: /etc/polkit-1/rules.d/50-mount-disks.rules
        owner: root
        group: root
        mode: '0644'

