- name: "System related stuff"
  hosts: localhost
  become: true

  tasks:
    - name: Install packages
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - bluez

    - name: allow hff to use bluetooth
      user:
        name: hff
        groups: bluetooth
        append: yes
