- name: "System related stuff"
  hosts: localhost
  become: true

  tasks:
    - name: Install packages
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - bluez
        - cups
        - cups-filters
        - system-config-printer
        - net-tools
        - avahi
        - nss-mdns

    - name: Enable services
      runit:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - cupsd
        - avahi-daemon

    - name: make sure hff is added to certain groups
      user:
        name: hff
        groups: "{{ item }}"
        append: yes
      loop:
        - bluetooth
        - users
        - docker
        - lp
        - lpadmin
