- name: "Install my terminal"
  hosts: localhost
  become: true

  tasks:
    - name: Install zsh
      xbps:
        name: zsh
        state: present

    - name: Set zsh as default shell
      command:
        cmd: usermod --shell /usr/bin/zsh hff

    - name: st build and font deps
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - make
        - pkg-config
        - fontconfig
        - libX11-devel
        - libXft-devel
        - font-unifont-bdf
        - liberation-fonts-ttf
        - font-inconsolata-otf

    - name: Get st source
      git:
        repo: "https://github.com/erkannt/my-st.git"
        version: "main"
        dest: /tmp/st

    - name: Install st
      make:
        chdir: /tmp/st
        target: install

