- name: Install window manager
  hosts: localhost
  become: true

  tasks:
    - name: dwm build dependencies
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - make
        - pkg-config
        - libX11-devel
        - libXinerama-devel
        - sharutils

    - name: Get dwm source
      git:
        repo: "https://github.com/erkannt/my-dwm.git"
        version: "main"
        dest: /tmp/dwm

    - name: Install dwm
      make:
        chdir: /tmp/dwm
        target: install

    - name: Get dwm-from-gdm
      git:
        repo: "https://github.com/erkannt/my-dwm-from-gdm.git"
        version: "master"
        dest: /tmp/dwm-from-gdm

    - name: Make dwm accesible from gdm and set launch script
      make:
        chdir: /tmp/dwm-from-gdm
        target: install

    - name: Install related tools
      xbps:
        name: "{{ item }}"
        state: present
      loop:
        - rofi
        - feh
        - dunst
        - xsetroot # needed by sb
        - unclutter-xfixes
        - imlib2-devel # needed for patched slock

    - name: Get slock
      git:
        repo: "https://github.com/erkannt/my-slock.git"
        dest: /tmp/slock

    - name: Install slock
      make:
        chdir: /tmp/slock
        target: install

    - name: Get sb (dwm menu bar thingo)
      git:
        repo: "https://github.com/erkannt/Backup-of-the-sb-dwm-status-bar.git"
        dest: /tmp/sb

    - name: Install sb
      make:
        chdir: /tmp/sb
        target: install

